### ISSUE TITLE
Vidzi: Error on upload attempt.

### ISSUE THREAD

**Issue by zaboca** [mcrapet/plowshare-modules-legacy#4] opened 2015-04-09 16:49 UTC
Throws an error when attempting to perform an upload using module vidzi_tv.
grep_form_by_name failed (sed): "name=file"

**Comment by Raziel-23** [comment] 2016-04-20 13:10
I cannot reproduce this error. For me uploading files works correctly. On a page there is a valid form named 'file'. Most probably the service was temporary down. I'm closing this issue.

**Closed by Raziel-23** 2016-04-20 13:10 UTC
