### ISSUE TITLE
Uptobox need update ?

### ISSUE THREAD

**Issue by Finch29** [mcrapet/plowshare-modules-legacy#135] opened 2017-03-12 07:39 UTC
Hi, 
My upload to uptobox.com not work :( Maybe it's the new method for upload on there servers ? :s 

[Error screen](https://i.imgur.com/obcKTR8.png) 

Anyone as the same problem ? 

Thx in advance ;)

**Comment by hriad** [comment] 2017-03-12 10:32
Same issue over here.

**Comment by Cinpph** [comment] 2017-03-12 21:20
They change some things on the website, Uptobox module need a update.

**Comment by zodman** [comment] 2017-03-22 02:03
+1 for me!

**Comment by zodman** [comment] 2017-03-22 05:44
PR #137  yeah!

**Comment by Finch29** [comment] 2017-03-22 07:50
Thx a lot @zodman :D !

**Comment by mcrapet** [comment] 2017-03-24 08:03
Seems fixed, closing.

**Comment by ddurdle** [comment] 2017-05-09 21:59
This error is back!

Seems the introduce a timeout at busy times where you have to wait 30 seconds for the button to appear useable.

**Comment by ddurdle** [comment] 2017-05-10 10:45
I think the issue is the red text (in french) about 50% off premium for 15 euros.  If you use a premium account, it works, otherwise, it gets confused finding the link.

**Comment by mcrapet** [comment] 2017-05-10 17:28
Hi,
I confirm that parsing of wait message is not good anymore.

**Closed** 2017-09-15 04:58 UTC
